<?php
    $apikey = "rzp_test_R8d4XFJwLWyHd2";
?>
<?php
session_start();
include "backend/db_connect.php";

$claim_id = intval($_GET['claim_id'] ?? 0);

$stmt = $conn->prepare("SELECT * FROM claims WHERE id = ?");
$stmt->bind_param("i", $claim_id);
$stmt->execute();
$result = $stmt->get_result();

if ($claim = $result->fetch_assoc()) {
    // ✅ Correct field for bill
    $bill = $claim['total_bill'];  
}
?>


<form action="" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo intval($claim['total_bill'] * 100); ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="campusfood"
    data-description="we want to save foods"
    data-image="🌱"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['phone'];?>"
    data-theme.color="#3de240ff"
></script>



<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

